import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import React, { useState, useEffect } from "react";

const Home: NextPage = () => {
  useEffect(() => {
    const ws = new WebSocket("ws://localhost:8000/ws/todo/");
    ws.onopen = () => {
      console.log("WebSocket Client Connected");
      ws.send(
        JSON.stringify({
          action: "list",
          request_id: new Date().getTime(),
        })
      );
    };

    ws.onmessage = (message: any) => {
      let allData = JSON.parse(message.data);
      console.log(allData);
      console.log("hello");
    };
    ws.onerror = function () {
      console.log("Connection Error");
    };
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}></main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
